### ISSUE TITLE
Описать целевую платформу и системные требования и ограничения

### ISSUE THREAD

**Issue by re1nex** [re1nex/portan-ignis#122]

**Comment by mashaverdina** [comment]
Как-то странно выглядит список
![Screenshot 2020-03-28 at 19.49.34.png](https://images.zenhubusercontent.com/5c6d7136df0733a30558e3ac/61dd364a-d41a-4881-9d8e-02e9cee7e5b0)

Еще хочется увидеть хотя бы требования к оперативной и видео-памяти.
