### ISSUE TITLE
Описание продукта

### ISSUE THREAD

**Issue by re1nex** [re1nex/portan-ignis#2]
Создать описание продукта на русском и английском языках

**Comment by mashaverdina** [comment]
> Компьютерная игра в жанре платформера с элементами головоломки для платформы PC

В жанре платформер (без "а"), для PC (без тут, наверное, лучше).
Если получится разбить второе предложение на 2 более коротких - будет здорово.

> The player controls a character with a light source (Ignis)

Может тут лучше наоборот with an Ignis (light sourse)?

> for advancement by level

Не уверена, правильно ли это. to move further in level (а in ли тут?)? to advance further in level?

В целом хорошо бы текст на английском причесать. Он сейчас калька с русского, а некоторые вещи на английском строят немного не так. Если есть возможность подключить кого-то, кто очень хорошо в этом, или просто уделить больше внимание, то будет здорово. Если нет, то так нормально.
