### ISSUE TITLE
Релиз и Release notes

### ISSUE THREAD

**Issue by re1nex** [re1nex/portan-ignis#24]

**Comment by re1nex** [comment]
v1.0.0
+тестовый уровень. Коробка с небольшой стилизацией для проведения тестирований остальных компонент
+механика игрока. Движения игрока по уровню и его взаимодейтсвие с объектами уровня
+механика вражеского героя. Движение вражеского персонажа по уровню, реакция на свет и игрока
+факел игрока. Модель и взаимодейтсвие с персонажем
+факелы на уровне. Модель и взаимодейтсвие с персонажем
+освещение
+камера

// на проверку

**Comment by mashaverdina** [comment]
Как выяснили в слаке, наверное, 0.1.0. После "+" лучше поставить пробелы, и слова начать с большой буквы (в некоторых пунктах есть отдельные предложения, а для единообразия лучше тогда сделать все с большой). А так можно релизить :)

**Comment by re1nex** [comment]
done
