### ISSUE TITLE
Инструкция по запуску

### ISSUE THREAD

**Issue by re1nex** [re1nex/portan-ignis#31]

**Comment by mashaverdina** [comment]
Это инструкция по запуску для пользователя. У вас будет установщик? Кстати, надо это хотя бы на 4й спринт вынести и начать крепить к релизам. Вот исходя из того, что у вас будет, написать инструкцию для пользователя

**Comment by mashaverdina** [comment]
Давайте ориентироваться на то, что вы будете прикреплять инсталятор к релизу, тогда его оттуда будет легко брать за 1 клик.
